site_name: PyFPDF
site_url: https://github.com/reingart/pyfpdf
repo_url: https://github.com/reingart/pyfpdf.git
site_description: Simple PDF generation for Python (FPDF PHP port)
docs_dir: docs
site_dir: html
markdown_extensions: [toc,fenced_code]
use_directory_urls: false
theme: readthedocs
pages:
- [index.md, "Project Home"]
- [ProjectHome.md, "Project Home"]
- [ReferenceManual.md, "Reference manual"]
- [Tutorial.md, "Tutorial"]
- [Tutorial-es.md, "Tutorial (Spanish translation)"]
- [FAQ.md, "FAQ (Frequently asked questions)"]
- [Python3.md, "Python 3"]
- [Templates.md, "Templates"]
- [Unicode.md, "Unicode"]
- [Web2Py.md, "Web2Py framework"]
- [Testing.md, "Testing"]
- [Development.md, "Development"]
- ["reference/AcceptPageBreak.md", "Reference manual", "accept_page_break"]
- ["reference/AddFont.md", "Reference manual", "add_font"]
- ["reference/AddLink.md", "Reference manual", "add_link"]
- ["reference/AddPage.md", "Reference manual", "add_page"]
- ["reference/AliasNbPages.md", "Reference manual", "alias_nb_pages"]
- ["reference/Cell.md", "Reference manual", "cell"]
- ["reference/Close.md", "Reference manual", "close"]
- ["reference/DashedLine.md", "Reference manual", "dashed_line"]
- ["reference/Ellipse.md", "Reference manual", "ellipse"]
- ["reference/Error.md", "Reference manual", "error"]
- ["reference/FPDF.md", "Reference manual", "FPDF"]
- ["reference/Footer.md", "Reference manual", "footer"]
- ["reference/GetStringWidth.md", "Reference manual", "get_string_width"]
- ["reference/GetX.md", "Reference manual", "get_x"]
- ["reference/GetY.md", "Reference manual", "get_y"]
- ["reference/Header.md", "Reference manual", "header"]
- ["reference/Image.md", "Reference manual", "image"]
- ["reference/Line.md", "Reference manual", "line"]
- ["reference/Link.md", "Reference manual", "link"]
- ["reference/Ln.md", "Reference manual", "ln"]
- ["reference/MultiCell.md", "Reference manual", "multi_cell"]
- ["reference/Open.md", "Reference manual", "open"]
- ["reference/Output.md", "Reference manual", "output"]
- ["reference/PageNo.md", "Reference manual", "page_no"]
- ["reference/Rect.md", "Reference manual", "rect"]
- ["reference/SetAuthor.md", "Reference manual", "set_author"]
- ["reference/SetAutoPageBreak.md", "Reference manual", "set_auto_page_break"]
- ["reference/SetCompression.md", "Reference manual", "set_compression"]
- ["reference/SetCreator.md", "Reference manual", "set_creator"]
- ["reference/SetDisplayMode.md", "Reference manual", "set_display_mode"]
- ["reference/SetDrawColor.md", "Reference manual", "set_draw_color"]
- ["reference/SetFillColor.md", "Reference manual", "set_fill_color"]
- ["reference/SetFont.md", "Reference manual", "set_font"]
- ["reference/SetFontSize.md", "Reference manual", "set_font_size"]
- ["reference/SetKeywords.md", "Reference manual", "set_keywords"]
- ["reference/SetLeftMargin.md", "Reference manual", "set_left_margin"]
- ["reference/SetLineWidth.md", "Reference manual", "set_line_width"]
- ["reference/SetLink.md", "Reference manual", "set_link"]
- ["reference/SetMargins.md", "Reference manual", "set_margins"]
- ["reference/SetRightMargin.md", "Reference manual", "set_right_margin"]
- ["reference/SetStretching.md", "Reference manual", "set_stretching"]
- ["reference/SetSubject.md", "Reference manual", "set_subject"]
- ["reference/SetTextColor.md", "Reference manual", "set_text_color"]
- ["reference/SetTitle.md", "Reference manual", "set_title"]
- ["reference/SetTopMargin.md", "Reference manual", "set_top_margin"]
- ["reference/SetX.md", "Reference manual", "set_x"]
- ["reference/SetXY.md", "Reference manual", "set_xy"]
- ["reference/SetY.md", "Reference manual", "set_y"]
- ["reference/Text.md", "Reference manual", "text"]
- ["reference/Write.md", "Reference manual", "write"]
- ["reference/WriteHTML.md", "Reference manual", "write_html"]

